namespace ZaraGON.Application.ConfigGeneration;

public sealed class ApacheConfigGenerator
{
    public string Generate(
        string serverRoot,
        string documentRoot,
        int listenPort,
        string phpModulePath,
        string phpPath,
        string logDir,
        string vhostsConfPath,
        string? sitesEnabledDir = null,
        bool sslEnabled = false,
        int sslPort = 8443,
        string? sslDir = null,
        string? aliasDir = null)
    {
        // Normalize to forward slashes for Apache config
        serverRoot = serverRoot.Replace('\\', '/');
        documentRoot = documentRoot.Replace('\\', '/');
        phpModulePath = phpModulePath.Replace('\\', '/');
        phpPath = phpPath.Replace('\\', '/');
        logDir = logDir.Replace('\\', '/');
        vhostsConfPath = vhostsConfPath.Replace('\\', '/');

        var sitesInclude = "";
        if (!string.IsNullOrEmpty(sitesEnabledDir))
        {
            sitesEnabledDir = sitesEnabledDir.Replace('\\', '/');
            sitesInclude = $"\n# Auto Virtual Hosts\nIncludeOptional \"{sitesEnabledDir}/*.conf\"";
        }

        var aliasInclude = "";
        if (!string.IsNullOrEmpty(aliasDir))
        {
            aliasDir = aliasDir.Replace('\\', '/');
            aliasInclude = $"\n# Application Aliases (phpMyAdmin, etc.)\nIncludeOptional \"{aliasDir}/*.conf\"";
        }

        var sslConfig = "";
        if (sslEnabled && !string.IsNullOrEmpty(sslDir))
        {
            sslDir = sslDir.Replace('\\', '/');
            sslConfig = $"""

            # SSL
            LoadModule ssl_module modules/mod_ssl.so
            Listen 127.0.0.1:{sslPort}
            SSLRandomSeed startup builtin
            SSLRandomSeed connect builtin
            """;
        }

        return $$"""
            # Generated by ZaraGON - Do not edit manually
            # Last generated: {{DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}} UTC

            ServerRoot "{{serverRoot}}"
            Listen 127.0.0.1:{{listenPort}}

            # Modules
            LoadModule access_compat_module modules/mod_access_compat.so
            LoadModule actions_module modules/mod_actions.so
            LoadModule alias_module modules/mod_alias.so
            LoadModule allowmethods_module modules/mod_allowmethods.so
            LoadModule auth_basic_module modules/mod_auth_basic.so
            LoadModule authn_core_module modules/mod_authn_core.so
            LoadModule authn_file_module modules/mod_authn_file.so
            LoadModule authz_core_module modules/mod_authz_core.so
            LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
            LoadModule authz_host_module modules/mod_authz_host.so
            LoadModule authz_user_module modules/mod_authz_user.so
            LoadModule autoindex_module modules/mod_autoindex.so
            LoadModule cgi_module modules/mod_cgi.so
            LoadModule dir_module modules/mod_dir.so
            LoadModule env_module modules/mod_env.so
            LoadModule headers_module modules/mod_headers.so
            LoadModule include_module modules/mod_include.so
            LoadModule isapi_module modules/mod_isapi.so
            LoadModule log_config_module modules/mod_log_config.so
            LoadModule mime_module modules/mod_mime.so
            LoadModule negotiation_module modules/mod_negotiation.so
            LoadModule rewrite_module modules/mod_rewrite.so
            LoadModule setenvif_module modules/mod_setenvif.so
            {{sslConfig}}

            # PHP Module
            LoadModule php_module "{{phpModulePath}}"
            PHPIniDir "{{phpPath}}"

            ServerAdmin admin@localhost
            ServerName localhost:{{listenPort}}

            <Directory />
                AllowOverride None
                Require all denied
            </Directory>

            DocumentRoot "{{documentRoot}}"
            <Directory "{{documentRoot}}">
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
            </Directory>

            <IfModule dir_module>
                DirectoryIndex index.php index.html
            </IfModule>

            <FilesMatch "\.php$">
                SetHandler application/x-httpd-php
            </FilesMatch>

            ErrorLog "{{logDir}}/error.log"
            LogLevel warn

            <IfModule log_config_module>
                LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
                LogFormat "%h %l %u %t \"%r\" %>s %b" common
                CustomLog "{{logDir}}/access.log" combined
            </IfModule>

            <IfModule mime_module>
                TypesConfig conf/mime.types
                AddType application/x-httpd-php .php
                AddType application/x-compress .Z
                AddType application/x-gzip .gz .tgz
            </IfModule>

            # Virtual Hosts (manual profiles)
            Include "{{vhostsConfPath}}"
            {{sitesInclude}}
            {{aliasInclude}}
            """;
    }
}
