using ZaraGON.Core.Models;

namespace ZaraGON.Application.ConfigGeneration;

public sealed class MariaDbConfigGenerator
{
    public string Generate(
        string baseDir,
        string dataDir,
        int port,
        string logDir,
        MariaDbSettings? settings = null)
    {
        settings ??= new MariaDbSettings();

        // MariaDB on Windows needs forward slashes in paths
        baseDir = baseDir.Replace('\\', '/');
        dataDir = dataDir.Replace('\\', '/');
        var errorLogPath = Path.Combine(logDir, "mariadb-error.log").Replace('\\', '/');

        return $"""
            # Generated by ZaraGON - Do not edit manually
            # Last generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC

            [mysqld]
            port={port}
            bind-address=127.0.0.1
            basedir="{baseDir}"
            datadir="{dataDir}"

            # InnoDB
            innodb_buffer_pool_size={settings.InnodbBufferPoolSize}
            innodb_log_file_size=48M

            # Connections
            max_connections={settings.MaxConnections}
            max_allowed_packet={settings.MaxAllowedPacket}

            # Performance
            skip-name-resolve
            performance_schema=OFF
            table_open_cache=2000

            # Logging
            log_error="{errorLogPath}"

            # Character set
            character-set-server=utf8mb4
            collation-server=utf8mb4_unicode_ci

            [client]
            port={port}
            """;
    }
}
