using ZaraGON.Core.Models;

namespace ZaraGON.Application.ConfigGeneration;

public sealed class PhpIniGenerator
{
    public string Generate(
        string extensionDir,
        IEnumerable<string> enabledExtensions,
        string? tempDir = null,
        PhpSettings? settings = null,
        string? caCertPath = null)
    {
        settings ??= new PhpSettings();
        extensionDir = extensionDir.Replace('\\', '/');
        tempDir = (tempDir ?? Path.GetTempPath()).Replace('\\', '/');
        var caCert = !string.IsNullOrEmpty(caCertPath) && File.Exists(caCertPath)
            ? caCertPath.Replace('\\', '/')
            : "";

        // Only enable opcache if the DLL exists (some PHP builds don't ship it separately)
        var hasOpcache = File.Exists(Path.Combine(extensionDir.Replace('/', '\\'), "php_opcache.dll"))
            || File.Exists(Path.Combine(Path.GetDirectoryName(extensionDir.Replace('/', '\\'))!, "php_opcache.dll"));

        var displayErrors = settings.DisplayErrors ? "On" : "Off";

        var extensionLines = enabledExtensions
            .Select(ext => $"extension={ext}")
            .OrderBy(x => x);

        var allExtensionLines = string.Join(Environment.NewLine, extensionLines);

        return $"""
            ; Generated by ZaraGON - Do not edit manually
            ; Last generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC

            [PHP]
            engine = On
            short_open_tag = Off
            precision = 14
            output_buffering = 4096
            zlib.output_compression = Off

            implicit_flush = Off
            serialize_precision = -1

            zend.enable_gc = On

            ; Error handling
            error_reporting = {settings.ErrorReporting}
            display_errors = {displayErrors}
            display_startup_errors = {displayErrors}
            log_errors = On
            error_log = php_errors.log
            log_errors_max_len = 1024
            ignore_repeated_errors = Off

            ; Resource limits
            max_execution_time = {settings.MaxExecutionTime}
            max_input_time = {settings.MaxInputTime}
            memory_limit = {settings.MemoryLimit}

            ; Data handling
            post_max_size = {settings.PostMaxSize}
            default_mimetype = "text/html"
            default_charset = "UTF-8"

            ; File uploads
            file_uploads = On
            upload_max_filesize = {settings.UploadMaxFilesize}
            max_file_uploads = {settings.MaxFileUploads}

            ; Input limits
            max_input_vars = {settings.MaxInputVars}

            ; Paths and directories
            extension_dir = "{extensionDir}"
            sys_temp_dir = "{tempDir}"
            enable_dl = Off

            ; Extensions
            {allExtensionLines}

            ; Date
            [Date]
            date.timezone = {settings.DateTimezone}

            ; Session
            [Session]
            session.save_handler = files
            session.use_strict_mode = 0
            session.use_cookies = 1
            session.use_only_cookies = 1
            session.name = PHPSESSID
            session.auto_start = 0
            session.cookie_lifetime = 0
            session.gc_maxlifetime = 1440

            ; mbstring
            [mbstring]
            mbstring.language = neutral

            ; cURL
            [curl]
            curl.cainfo = "{caCert}"

            ; OpenSSL
            [openssl]
            openssl.cafile = "{caCert}"

            {(hasOpcache ? """
            ; OPcache
            [opcache]
            zend_extension=opcache
            opcache.enable=1
            opcache.memory_consumption=128
            opcache.max_accelerated_files=10000
            opcache.revalidate_freq=2
            opcache.validate_timestamps=1
            """ : "; OPcache not available for this PHP build")}

            ; Realpath cache
            realpath_cache_size=4096K
            realpath_cache_ttl=600

            ; Mail
            [mail function]
            SMTP = 127.0.0.1
            smtp_port = 1025
            sendmail_from = zaragon@localhost
            """;
    }
}
